name: Publish Python Package to TestPyPI

on:
  push:

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }} # Use TestPyPI credentials from GitHub Secrets
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }} # Use TestPyPI credentials from GitHub Secrets
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
